# Copia este contenido en Streamlit Cloud > App > Settings > Secrets
# o localmente en .streamlit/secrets.toml

GOOGLE_SHEET_CSV_URL = "https://docs.google.com/spreadsheets/d/SPREADSHEET_ID/export?format=csv&gid=GID"